"""Writes price cache-lifetime vectors from the desktop's own TTL function.

The mobile app had no cache lifetime at all: every construction of the Assets
screen called the providers, so switching tabs, recording a transaction, or
tapping a period chip each cost a live round trip that nobody asked for. The
desktop has answered this since it was written -- ``services/price_service.py``
is "cache-first, dinamik TTL'li" -- so the fix is a port rather than a number
somebody picked.

The rules are not written here. `get_ttl_minutes` is called for each row, so
the market-hours boundaries, the weekday test and the infinities come from the
desktop module itself. What this file chooses is the CASES: every asset kind,
each side of both market edges, and both sides of the weekend.

Istanbul is fixed at UTC+3 on both sides -- Turkey has kept no daylight saving
since 2016 -- which is why the mobile port needs no timezone database.

    cd <desktop checkout>
    ./aeadvenv/bin/python <mobile>/tool/emit_price_ttl_vectors.py \\
        <mobile>/test/price_ttl_vectors.txt
"""

from __future__ import annotations

import os
import sys
from datetime import datetime

if len(sys.argv) != 2:
    raise SystemExit(__doc__)

destination = os.path.abspath(sys.argv[1])
sys.path.insert(0, os.getcwd())

from services import price_service  # noqa: E402


ISTANBUL = price_service.ISTANBUL


def at(year: int, month: int, day: int, hour: int, minute: int) -> datetime:
    return datetime(year, month, day, hour, minute, tzinfo=ISTANBUL)


# 2026-09-02 is a Wednesday; 2026-09-05 a Saturday; 2026-09-06 a Sunday.
# The market edges are 09:55 and 18:10, so each is probed on both sides and
# exactly on the boundary -- the minute a `<=` becomes a `<` is precisely the
# kind of difference a hand-written expectation hides.
MOMENTS = [
    ("weekday-premarket", at(2026, 9, 2, 9, 54)),
    ("weekday-open-edge", at(2026, 9, 2, 9, 55)),
    ("weekday-midday", at(2026, 9, 2, 13, 0)),
    ("weekday-close-edge", at(2026, 9, 2, 18, 10)),
    ("weekday-postmarket", at(2026, 9, 2, 18, 11)),
    ("weekday-midnight", at(2026, 9, 2, 0, 0)),
    ("saturday-midday", at(2026, 9, 5, 13, 0)),
    ("sunday-midday", at(2026, 9, 6, 13, 0)),
]

# Every spelling the mobile side can hand in, including the ones a restored
# desktop database already stores.
ASSET_TYPES = [
    "Kripto",
    "CRYPTO",
    "KRİPTO",
    "Hisse",
    "STOCK",
    "HİSSE SENEDİ",
    "Döviz",
    "DÖVİZ",
    "FOREX",
    "Altın",
    "GOLD",
    "FX_GOLD",
    "Tahvil",
    "Diğer",
    "",
]

with open(destination, "w", encoding="utf-8", newline="\n") as output:
    output.write(
        "# asset_type|moment_iso|ttl_minutes "
        "— generated by services/price_service.get_ttl_minutes\n"
        "# 'inf' is a cache that never needs refreshing: a closed market\n"
    )
    for asset_type in ASSET_TYPES:
        for _label, moment in MOMENTS:
            ttl = price_service.get_ttl_minutes(asset_type, now=moment)
            rendered = "inf" if ttl == price_service.INFINITE_TTL else str(ttl)
            output.write(
                "%s|%s|%s\n" % (asset_type, moment.isoformat(), rendered)
            )
