"""Emits dashboard-period vectors from the desktop's own module.

`services/dashboard_period_service.py` is pure: it imports nothing but
`utils.financial_decimal`, and its `calculate_balance_change` takes the
balance reader as an ARGUMENT. So it can be called directly, with a stub
reader, and every boundary it draws comes out of its own code.

The percentage rule is the reason this fixture exists. "Change from zero" has
no finite percentage, and the desktop refuses to invent one — while zero to
zero is the single well-defined no-change case and answers 0%. Those two lines
sit next to each other and are easy to get backwards.

    cd <desktop checkout>
    ./aeadvenv/bin/python <mobile>/tool/emit_period_vectors.py \\
        <mobile>/test/period_vectors.txt
"""

from __future__ import annotations

import datetime
import os
import sys

if len(sys.argv) != 2:
    raise SystemExit(__doc__)

destination = os.path.abspath(sys.argv[1])
sys.path.insert(0, os.getcwd())

from services.dashboard_period_service import (  # noqa: E402
    calculate_balance_change,
    percentage_change,
    period_bounds,
)


# The mobile enum's names, against the desktop's Turkish UI strings. That
# mapping is itself a claim worth pinning: the desktop passes its own labels
# as the filter value, and the port replaced them with an enum.
PERIODS = [
    ("today", "Bugün"),
    ("week", "1 Hafta"),
    ("month", "1 Ay"),
    ("year", "1 Yıl"),
    ("allTime", "Hayat Boyu"),
]

TODAY = datetime.date(2026, 8, 27)

lines = [
    "# Generated by CALLING services/dashboard_period_service.py.",
    "#",
    "# BOUNDS|period|today|start|end — start empty means no lower bound",
    "# PERCENT|startingBalance|currentBalance|percentage — empty means the",
    "#   desktop refuses to give one",
    "# CHANGE|period|today|startingBalance|currentBalance|baselineDate"
    "|nominalChange|percentage — an empty startingBalance is a baseline the",
    "#   ledger cannot answer for",
]

for name, filter_text in PERIODS:
    start, end = period_bounds(filter_text, TODAY)
    lines.append(
        f"BOUNDS|{name}|{TODAY.isoformat()}"
        f"|{'' if start is None else start.isoformat()}|{end.isoformat()}"
    )


PERCENT_CASES = [
    ("1000", "1250"),
    ("1000", "750"),
    ("1000", "1000"),
    # A negative baseline: the divisor is its ABSOLUTE value, so climbing out
    # of debt reads as a gain rather than a loss.
    ("-1000", "-500"),
    ("-1000", "-1500"),
    # The two zero rules, side by side.
    ("0", "0"),
    ("0", "500"),
    ("0", "-500"),
    ("2500.50", "3000.75"),
]

for start_balance, current in PERCENT_CASES:
    value = percentage_change(start_balance, current)
    lines.append(
        f"PERCENT|{start_balance}|{current}"
        f"|{'' if value is None else repr(value)}"
    )

# A baseline the ledger cannot answer for at all.
lines.append(f"PERCENT||1000|{'' if percentage_change(None, '1000') is None else 'x'}")


CHANGE_CASES = [
    ("today", "Bugün", "1000", "1250"),
    ("week", "1 Hafta", "1000", "900"),
    ("month", "1 Ay", "0", "0"),
    ("month", "1 Ay", "0", "400"),
    ("year", "1 Yıl", "12000.40", "15000.10"),
    # No baseline: `balance_reader` answers with nothing, which is what
    # "before the ledger started" looks like from here.
    ("month", "1 Ay", None, "1250"),
    # Whole history: no lower bound, so the change IS the balance and there
    # is no percentage to give.
    ("allTime", "Hayat Boyu", "1000", "1250"),
]

for name, filter_text, starting, current in CHANGE_CASES:
    def reader(_date, starting=starting):
        return None if starting is None else {"total_balance": starting}

    result = calculate_balance_change(
        filter_text,
        current,
        today=TODAY,
        balance_reader=reader,
    )
    baseline = result.get("baseline_date")
    nominal = result["nominal_change"]
    percentage = result["percentage"]
    lines.append(
        f"CHANGE|{name}|{TODAY.isoformat()}|{starting or ''}|{current}"
        f"|{'' if baseline is None else baseline.isoformat()}"
        f"|{'' if nominal is None else nominal}"
        f"|{'' if percentage is None else repr(percentage)}"
    )


with open(destination, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")

print(f"{len(lines)} lines")
