"""Writes ticker-classification vectors from the desktop's own mapper.

The mobile app deliberately does not use the desktop's provider identifiers,
but its classification of stored asset types and internal gold codes has to
remain identical. This script reads that classification straight from
``utils/ticker_mapper.py`` so the Dart test does not verify a hand-written
copy of it.

    cd <desktop checkout>
    ./aeadvenv/bin/python <mobile>/tool/emit_ticker_classification.py \
        <mobile>/test/ticker_classification_vectors.txt
"""

from __future__ import annotations

import os
import sys

if len(sys.argv) != 2:
    raise SystemExit(__doc__)

destination = os.path.abspath(sys.argv[1])
sys.path.insert(0, os.getcwd())

from utils import ticker_mapper


# These inputs cover every desktop branch and every stored UI asset type. The
# expectations below are *not* written here: kind, gold membership and the
# multiplier are read from the desktop module for each row.
CASES = [
    # `assetTypes` in the mobile service.
    ("ASELS", "Hisse"),
    ("BOND", "Tahvil"),
    ("USD", "Döviz"),
    ("BTC", "Kripto"),
    ("OTHER", "Diğer"),
    # Every desktop crypto spelling, including the dotted/dotless-I pairs.
    ("BTC", "CRYPTO"),
    ("BTC", "KRIPTO"),
    ("BTC", "KRİPTO"),
    ("BTC", "KRIPTO PARA"),
    ("BTC", "KRİPTO PARA"),
    # Every desktop stock spelling.
    ("ASELS", "STOCK"),
    ("ASELS", "HISSE"),
    ("ASELS", "HİSSE"),
    ("ASELS", "HİSSE SENEDİ"),
    ("ASELS", "HISSE SENEDI"),
    # Every desktop FX/gold spelling.
    ("USD", "FX_GOLD"),
    ("USD", "DÖVIZ"),
    ("USD", "DÖVİZ"),
    ("USD", "FOREX"),
    ("USD", "ALTIN"),
    ("USD", "GOLD"),
    # Each internal gold code and its desktop multiplier, where it has one.
    ("ALTIN", "Altın"),
    ("GOLD", "Altın"),
    ("GRAM", "Altın"),
    ("XAU", "Altın"),
    ("GOLD-ONS", "Altın"),
    ("GOLD-CEYREK", "Altın"),
    ("GOLD-YARIM", "Altın"),
    ("GOLD-TAM", "Altın"),
    # Currency rules, the empty symbol, and type fall-through behaviour.
    ("TRY", "Döviz"),
    ("", "Döviz"),
    ("US1", "Döviz"),
    ("ÄBC", "Döviz"),
    ("BOND", "Bilinmeyen"),
    ("USD", ""),
]

with open(destination, "w", encoding="utf-8", newline="\n") as output:
    output.write(
        "# symbol|asset_type|kind|is_gold|multiplier "
        "— generated by utils/ticker_mapper.py\n"
    )
    for symbol, asset_type in CASES:
        code = (symbol or "").strip().upper()
        kind = ticker_mapper.normalize_asset_type(asset_type)
        is_gold = code in ticker_mapper._GOLD_INTERNAL
        multiplier = ticker_mapper.gold_multiplier(symbol)
        output.write(
            "%s|%s|%s|%s|%s\n"
            % (
                symbol,
                asset_type,
                kind,
                str(is_gold).lower(),
                "" if multiplier is None else multiplier,
            )
        )
