"""Regenerates `lib/data/default_categories.dart` from the desktop's own list.

These names are DATA: the budget, the distribution chart and the subscription
radar all match them as literals, so a hand-transcribed typo would quietly
split a category in two across the two apps. The list is read out of
`database/init_db.py` rather than copied.

    cd <desktop checkout>
    python3 tool/emit_default_categories.py > \
        <mobile>/lib/data/default_categories.dart
"""
import ast
import io
import sys

src = open("database/init_db.py", encoding="utf-8").read()
start = src.index("default_categories = [")
end = src.index("]", src.index('("Varlık Alımı", "expense", "extra")', start)) + 1
rows = ast.literal_eval(src[start + len("default_categories = "):end])

# The three the desktop adds afterwards if they are missing.
seen = {(name, kind) for name, kind, _ in rows}
for row in [
    ("Varlık Alımı", "expense", "extra"),
    ("Varlık Satışı", "income", "extra"),
    ("Dijital Abonelik", "expense", "extra"),
]:
    if (row[0], row[1]) not in seen:
        rows.append(row)
        seen.add((row[0], row[1]))

out = io.StringIO()
out.write('''/// The categories the desktop seeds into a new database.
///
/// GENERATED by `tool/emit_default_categories.py` from `database/init_db.py`'s
/// own `default_categories` list, plus the three it adds afterwards if
/// missing. Not hand-transcribed: these names are DATA, matched as literals
/// by the budget, the distribution chart and the subscription radar, so a
/// typo here would quietly split a category in two across the two apps.
///
/// `importance` is 'main' or 'extra' — the desktop's own split between what a
/// household must pay and what it chooses to.
library;

/// (name, type, importance).
const List<(String, String, String)> defaultCategories = [
''')
for name, kind, importance in rows:
    out.write("  ('%s', '%s', '%s'),\n" % (name.replace("'", "\\'"), kind, importance))
out.write("];\n")
sys.stdout.write(out.getvalue())
