"""Emits main/extra bucketing vectors from the desktop's OWN summariser.

The port in `lib/services/financial_summary.dart` decides which of four
buckets a transaction lands in from its type and its category's `importance`.
That mapping is small enough to look obvious and is not: 'main' means
`main_income` for income but `essential_expense` for an expense, a NULL
importance is 'extra' rather than an error, and a type that is neither income
nor expense is DROPPED rather than counted as zero. Writing those expectations
by hand in the Dart test would test my reading of
`services/financial_summary_service.py`, so they are read out of it instead.

Each case is summarised ALONE, so a row landing in the wrong bucket names
itself instead of being hidden inside a total. The last line sums every case
together, which is the one an accumulation bug shows up in.

    cd <desktop checkout>
    ./aeadvenv/bin/python <mobile>/tool/emit_summary_vectors.py \
        <mobile>/test/summary_vectors.txt
"""

from __future__ import annotations

import os
import sys

if len(sys.argv) != 2:
    raise SystemExit(__doc__)

destination = os.path.abspath(sys.argv[1])
sys.path.insert(0, os.getcwd())

from database.db import SECRET_KEY
from services.financial_summary_service import summarize_transactions
from utils.crypto import encrypt


# Type spellings: the desktop accepts the English and the Turkish for both
# sides, and everything else falls through its `continue`. Importance: the two
# real values, NULL (a category with no row in `categories`), and a value from
# neither list — that last one must read as 'extra', not raise.
#
# The amounts are all DIFFERENT, and deliberately so: with one amount repeated
# down the column, two buckets swapped would produce the same file.
CASES = [
    ("income", "main", "1000.00"),
    ("income", "extra", "200.50"),
    ("income", None, "30.25"),
    ("income", "", "4.10"),
    ("income", "nonsense", "5.55"),
    ("Gelir", "main", "60000.00"),
    ("Gelir", "extra", "7000.75"),
    ("Gelir", None, "800.05"),
    ("expense", "main", "90.00"),
    ("expense", "extra", "12.34"),
    ("expense", None, "56.78"),
    ("expense", "", "1.01"),
    ("expense", "nonsense", "2.02"),
    ("Gider", "main", "345.67"),
    ("Gider", "extra", "89.10"),
    ("Gider", None, "11.11"),
    # Neither side. Dropped entirely — the amount must appear in no bucket.
    ("transfer", "main", "999999.99"),
    ("Devir", "extra", "888888.88"),
    ("", "main", "777777.77"),
]


def row(index, kind, importance, amount):
    return {
        "id": index,
        "amount": encrypt(amount, SECRET_KEY),
        "type": kind,
        "importance": importance,
    }


def fields(summary):
    return "|".join(
        str(value)
        for value in (
            summary.main_income,
            summary.extra_income,
            summary.essential_expense,
            summary.extra_expense,
        )
    )


lines = [
    "# type|importance|amount|main_income|extra_income|essential_expense"
    "|extra_expense",
    "# generated by services/financial_summary_service.py",
    "# an empty importance field is SQL NULL *or* the empty string — the"
    " desktop treats both as 'extra', which is why two cases here produce"
    " the same line",
    "# amounts are quoted as the desktop's Decimal prints them: a zero bucket"
    " is '0', not '0.00'. Compare numerically.",
]

for index, (kind, importance, amount) in enumerate(CASES, start=1):
    summary = summarize_transactions([row(index, kind, importance, amount)])
    stored = "" if importance is None else importance
    lines.append(f"{kind}|{stored}|{amount}|{fields(summary)}")

everything = [
    row(index, kind, importance, amount)
    for index, (kind, importance, amount) in enumerate(CASES, start=1)
]
lines.append(f"ALL|||{fields(summarize_transactions(everything))}")

with open(destination, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")
