"""Emits recovery-material and auth-tag vectors from the desktop's OWN module.

Every line is produced by `services.backup_service`, not by a
re-implementation, so a Dart port compared against it is compared against the
real thing rather than against someone's reading of it.

    cd <desktop checkout>
    python3 -m venv aeadvenv
    ./aeadvenv/bin/pip install pycryptodome platformdirs
    ./aeadvenv/bin/python <mobile>/tool/emit_backup_vectors.py > \
        <mobile>/test/backup_vectors.txt

The non-default round count near the end is not decoration: without it, a port
that ignored the count a package DECLARES and always used its own constant
would pass every other vector. The constant is swapped, not the algorithm, so
the payload still comes out of the module's own code path.
"""
import base64, json, os, sys

sys.path.insert(0, os.getcwd())
os.environ.setdefault("ARCHLENCE_TEST", "1")

from services import backup_service as bs

def b64(raw):
    return base64.b64encode(raw).decode("ascii")

print("# format: TYPE|fields...  — generated by services/backup_service.py")
print("# iterations are the module's own constant")
print("ITER|%d" % bs._RECOVERY_ITERATIONS)
print("AUTHCONTEXT|%s" % b64(bs._AUTH_CONTEXT))

# --- recovery material: wrap a known key under a known passphrase ---
cases = [
    (bytes(range(32)), "correct horse battery"),
    (bytes([0xAA] * 32), "a-passphrase-with-ünïcode"),
    (bytes([0] * 32), "twelve chars"),
]
for key, passphrase in cases:
    payload = bs.encrypt_recovery_material(key, passphrase)
    # Prove the module reads its own output back.
    assert bs.decrypt_recovery_material(payload, passphrase) == key
    print(
        "RECOVERY|%s|%s|%s|%s|%s|%s|%d"
        % (
            b64(key),
            passphrase,
            payload["salt"],
            payload["nonce"],
            payload["tag"],
            payload["ciphertext"],
            payload["iterations"],
        )
    )

# A payload at a NON-DEFAULT round count, still produced by the module's own
# code path (the constant is swapped, not the algorithm), so a port that
# ignores the count a package declares cannot pass.
saved = bs._RECOVERY_ITERATIONS
bs._RECOVERY_ITERATIONS = 150_000
try:
    key = bytes([0x5A] * 32)
    passphrase = "a-different-round-count"
    payload = bs.encrypt_recovery_material(key, passphrase)
    assert payload["iterations"] == 150_000
    assert bs.decrypt_recovery_material(payload, passphrase) == key
    print(
        "RECOVERY|%s|%s|%s|%s|%s|%s|%d"
        % (
            b64(key),
            passphrase,
            payload["salt"],
            payload["nonce"],
            payload["tag"],
            payload["ciphertext"],
            payload["iterations"],
        )
    )
finally:
    bs._RECOVERY_ITERATIONS = saved

# --- auth tag over metadata ---
metadata_cases = [
    {
        "format_version": 2,
        "created_at": "2026-08-26T09:00:00+00:00",
        "database_sha256": "a" * 64,
        "key_fingerprint": "b" * 64,
        "aead_records_verified": 7,
        "authentication_salt": b64(bytes(range(16))),
    },
    {
        "format_version": 2,
        "created_at": "2020-01-02T03:04:05+00:00",
        "database_sha256": "0" * 64,
        "key_fingerprint": "f" * 64,
        "aead_records_verified": 0,
        "authentication_salt": b64(bytes([0xFF] * 16)),
    },
]
for metadata in metadata_cases:
    for passphrase in ("correct horse battery", "twelve chars"):
        tag = bs._backup_auth_tag(metadata, passphrase)
        print(
            "AUTHTAG|%s|%s|%s"
            % (
                passphrase,
                json.dumps(metadata, sort_keys=True, separators=(",", ":")),
                tag,
            )
        )
