"""Emits calculator vectors from the desktop's OWN calculator methods.

The three financial calculators live on `mixins/calculator_mixin.py`, which is
a Kivy mixin: the methods read `self.<field>.text` and write
`self.<label>.text`. That makes them awkward to call and it does NOT make them
unreachable — the arithmetic is the desktop's, and transcribing it into this
script would test the transcription rather than the port.

**So the mixin is imported with its UI stubbed.** `kivy` and `kivymd` are not
installed in `aeadvenv` and are not needed: nothing the three methods below
touch comes from them. Fake modules go into `sys.modules` first, then the real
`CalculatorMixin` is imported and called against a duck-typed object whose
fields are plain strings. What comes back is the real method's own output.

If a future desktop version makes these methods reach into a real widget, this
script fails loudly at import rather than silently producing hand-derived
numbers.

    cd <desktop checkout>
    ./aeadvenv/bin/python <mobile>/tool/emit_calculator_vectors.py \\
        <mobile>/test/calculator_vectors.txt
"""

from __future__ import annotations

import os
import re
import sys
import types

if len(sys.argv) != 2:
    raise SystemExit(__doc__)

destination = os.path.abspath(sys.argv[1])
sys.path.insert(0, os.getcwd())


# --- the UI the mixin imports but these three methods never use ------------

class _Anything:
    """Stands in for a widget class the module imports at the top level."""

    def __init__(self, *args, **kwargs):
        pass

    def __getattr__(self, name):
        return _Anything()

    def __call__(self, *args, **kwargs):
        return _Anything()


def _fake(name, **attributes):
    module = types.ModuleType(name)
    for key, value in attributes.items():
        setattr(module, key, value)
    module.__getattr__ = lambda _name: _Anything()
    sys.modules[name] = module
    return module


for name in (
    "kivy",
    "kivy.uix",
    "kivy.uix.scrollview",
    "kivymd",
    "kivymd.uix",
    "kivymd.uix.button",
    "kivymd.uix.dialog",
    "kivymd.uix.textfield",
    "kivymd.uix.boxlayout",
    "kivymd.uix.gridlayout",
    "kivymd.uix.segmentedcontrol",
    "kivymd.uix.label",
):
    _fake(name)

_fake("kivy.metrics", dp=lambda value: value)
_fake("utils.toast", toast=lambda *args, **kwargs: _refused.append(args))
_fake("ui.theme")

_refused: list = []

from mixins.calculator_mixin import CalculatorMixin  # noqa: E402
from utils.calculator import evaluate_calculator_expression  # noqa: E402


class _Field:
    """A text field, as the mixin reads one."""

    def __init__(self, text=""):
        self.text = str(text)


class _Label:
    def __init__(self):
        self.text = ""
        self.theme_text_color = None
        self.text_color = None


class _Toggle:
    def __init__(self, disabled=True):
        self.disabled = disabled
        self.opacity = 0


class Harness(CalculatorMixin):
    """The mixin's fields, with nothing else attached.

    Every attribute here is one the three methods actually read. If the
    desktop grows a new one, `AttributeError` says so rather than this
    quietly producing a different answer.
    """

    def __init__(self):
        self.int_principal = _Field()
        self.int_rate = _Field()
        self.int_days = _Field()
        self.int_result_label = _Label()

        self.comp_principal = _Field()
        self.comp_rate = _Field()
        self.comp_time = _Field()
        self.comp_deposit = _Field()
        self.comp_result_label = _Label()

        self.loan_amount = _Field()
        self.loan_rate = _Field()
        self.loan_term = _Field()
        self.loan_custom_name = _Field()
        self.loan_result_label = _Label()
        self.loan_type = _Toggle(disabled=True)
        self.loan_type_selected = "İhtiyaç"
        self.custom_expenses = []
        self.loan_table_data = []
        self.loan_table_btn = _Toggle()
        self.add_debt_btn = _Toggle()
        self.last_calculated_loan = None


def _numbers(text):
    """Pulls the Turkish-formatted figures out of a result label, in order."""
    return re.findall(r"-?\d{1,3}(?:\.\d{3})*,\d{2}", text)


lines = [
    "# Vectors generated by CALLING mixins/calculator_mixin.py's own methods.",
    "# Figures are the desktop's own Turkish formatting, so a port has to",
    "# agree on the arithmetic AND on how it is written.",
    "#",
    "# INTEREST|principal|rate|days|netProfit|total",
    "# COMPOUND|principal|rate|years|monthlyDeposit|invested|profit|amount",
    "# LOAN|principal|monthlyRate|months|instalment|totalRepayment",
    "# LOANROW|principal|monthlyRate|months|month|instalment|principalPart"
    "|interestAndTax|remaining",
    "# REFUSED|kind|a|b|c — input the desktop refuses to compute at all",
    "# BASIC|expression|result — utils/calculator.py, called directly",
]


# --- simple deposit interest ------------------------------------------------

INTEREST_CASES = [
    ("10000", "45", "32"),
    ("10000", "45", "365"),
    ("250000", "38.5", "92"),
    ("1", "1", "1"),
    ("999999.99", "50", "180"),
]

for principal, rate, days in INTEREST_CASES:
    harness = Harness()
    harness.int_principal.text = principal
    harness.int_rate.text = rate
    harness.int_days.text = days
    harness.calculate_interest()
    figures = _numbers(harness.int_result_label.text)
    if len(figures) != 2:
        raise SystemExit(
            f"interest {principal}/{rate}/{days} gave {harness.int_result_label.text!r}"
        )
    lines.append(f"INTEREST|{principal}|{rate}|{days}|{figures[0]}|{figures[1]}")


# --- compound ---------------------------------------------------------------

COMPOUND_CASES = [
    ("10000", "30", "5", ""),
    ("10000", "30", "5", "500"),
    ("100000", "12.5", "10", "2500"),
    ("1000", "1", "1", ""),
    ("50000", "45", "3", "1"),
]

for principal, rate, years, deposit in COMPOUND_CASES:
    harness = Harness()
    harness.comp_principal.text = principal
    harness.comp_rate.text = rate
    harness.comp_time.text = years
    harness.comp_deposit.text = deposit
    harness.calculate_compound()
    figures = _numbers(harness.comp_result_label.text)
    if len(figures) != 3:
        raise SystemExit(
            f"compound {principal}/{rate}/{years}/{deposit} gave "
            f"{harness.comp_result_label.text!r}"
        )
    lines.append(
        f"COMPOUND|{principal}|{rate}|{years}|{deposit or '0'}"
        f"|{figures[0]}|{figures[1]}|{figures[2]}"
    )


# --- loan, in the basic mode this port covers -------------------------------

LOAN_CASES = [
    ("100000", "3.29", "12"),
    ("100000", "3.29", "36"),
    ("50000", "2.5", "24"),
    ("1000000", "4.15", "36"),
    ("15000", "1.99", "6"),
]

for principal, rate, months in LOAN_CASES:
    harness = Harness()
    harness.loan_amount.text = principal
    harness.loan_rate.text = rate
    harness.loan_term.text = months
    harness.calculate_loan()
    figures = _numbers(harness.loan_result_label.text)
    if len(figures) != 2:
        raise SystemExit(
            f"loan {principal}/{rate}/{months} gave "
            f"{harness.loan_result_label.text!r}"
        )
    lines.append(f"LOAN|{principal}|{rate}|{months}|{figures[0]}|{figures[1]}")

    # The amortisation schedule, straight out of `loan_table_data`. Only the
    # first, second and last months: the middle of a 36-row table proves
    # nothing the ends do not, and the LAST row is where a rounding error
    # accumulates into a balance that does not reach zero.
    rows = harness.loan_table_data
    for index in (0, 1, len(rows) - 1):
        month, instalment, _extra, _total, principal_part, interest_tax, balance = (
            rows[index]
        )
        lines.append(
            f"LOANROW|{principal}|{rate}|{months}|{month}|{instalment}"
            f"|{principal_part}|{interest_tax}|{balance}"
        )


# --- what the desktop refuses ----------------------------------------------

REFUSED = [
    ("INTEREST", "0", "45", "32"),
    ("INTEREST", "10000", "0", "32"),
    ("INTEREST", "10000", "45", "0"),
    ("INTEREST", "-5000", "45", "32"),
    ("COMPOUND", "0", "30", "5"),
    ("COMPOUND", "10000", "0", "5"),
    ("COMPOUND", "10000", "30", "0"),
    ("LOAN", "0", "3.29", "12"),
    ("LOAN", "100000", "0", "12"),
    ("LOAN", "100000", "3.29", "0"),
    # Over the 36-month cap that basic mode enforces.
    ("LOAN", "100000", "3.29", "37"),
]

for kind, a, b, c in REFUSED:
    harness = Harness()
    if kind == "INTEREST":
        harness.int_principal.text, harness.int_rate.text, harness.int_days.text = a, b, c
        harness.calculate_interest()
        produced = harness.int_result_label.text
    elif kind == "COMPOUND":
        harness.comp_principal.text, harness.comp_rate.text, harness.comp_time.text = a, b, c
        harness.calculate_compound()
        produced = harness.comp_result_label.text
    else:
        harness.loan_amount.text, harness.loan_rate.text, harness.loan_term.text = a, b, c
        harness.calculate_loan()
        produced = harness.loan_result_label.text
    if produced:
        raise SystemExit(f"{kind} {a}/{b}/{c} was expected to be refused")
    lines.append(f"REFUSED|{kind}|{a}|{b}|{c}")


# --- the basic calculator ---------------------------------------------------

BASIC_CASES = [
    "2+2",
    "10/4",
    "2*3+4",
    "2+3*4",
    "(2+3)*4",
    "10%3",
    "2**10",
    "-5+3",
    "sqrt(16)",
    "log(1000)",
    # Non-powers of ten, because Dart has no log10 and log(x)/ln10 is not the
    # same function: this is where a port that fakes it drifts by an ULP.
    "log(2)",
    "log(50)",
    "log(0.001)",
    "log(7)*log(13)",
    "sqrt(2)",
    "sin(1)",
    "cos(1)",
    "tan(1)",
    "pi",
    "1/3",
    "0.1+0.2",
    # Precedence and associativity, where a hand-written parser goes wrong:
    # `**` binds tighter than a unary minus on its left, its right operand may
    # itself be unary, and it associates to the RIGHT.
    "-2**2",
    "2**-2",
    "2**3**2",
    # Python's `%` takes the sign of the DIVISOR. Dart's `%` is always
    # non-negative and its `remainder` takes the sign of the dividend, so
    # neither operator is a drop-in and this line is what says so.
    "10%-3",
    "-10%3",
    # Literal shapes Python's tokenizer accepts.
    ".5+1",
    "1.",
    "1_000",
    "3 + 4 * 2 / ( 1 - 5 ) ** 2",
]

for expression in BASIC_CASES:
    value = evaluate_calculator_expression(expression)
    lines.append(f"BASIC|{expression}|{value!r}")

BASIC_REFUSED = [
    "",
    "   ",
    "1/0",
    "2**1000",
    "__import__('os')",
    "open('x')",
    "1+",
    "abs(-1)",
]

for expression in BASIC_REFUSED:
    try:
        evaluate_calculator_expression(expression)
    except Exception:
        lines.append(f"BASICREFUSED|{expression}")
    else:
        raise SystemExit(f"{expression!r} was expected to be refused")


with open(destination, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")

print(f"{len(lines)} lines")
