"""Writes the search-folding table from the desktop's OWN normalisation.

`services/search_service.py`'s `normalize()` is what makes Turkish search work:
it folds case, decomposes accents and drops them, and maps dotless `ı` onto
`i` — so "sirket" finds "Şirket" and "ISI" finds "ısı". Dart has no Unicode
normalisation in its core library and this project takes no dependency for
one, so the answer is a TABLE, computed by the desktop's own steps rather than
transcribed.

**Why a per-character table is exactly equivalent, and not an approximation.**
`normalize()` is `casefold` -> NFKD -> drop combining marks -> `ı`->`i` ->
collapse whitespace. Every step but the last is per-character, and the last is
applied to the assembled string here too. That equivalence is not assumed: this
script CHECKS it over every codepoint it covers and over 60,000 random strings
built from them, and refuses to write the file if a single one disagrees.

The table holds only the codepoints whose folding CHANGES them, and only below
`COVERED_BELOW`. Above that a character passes through untouched — see the
generated file's own comment for what that means and why it is the safe
direction for a Turkish finance app.

    cd <desktop checkout>
    ./aeadvenv/bin/python <mobile>/tool/emit_search_folding.py \\
        <mobile>/lib/services/search_folding.dart \\
        <mobile>/test/search_folding_vectors.txt
"""

from __future__ import annotations

import os
import random
import sys
import unicodedata

if len(sys.argv) != 3:
    raise SystemExit(__doc__)

table_path = os.path.abspath(sys.argv[1])
vectors_path = os.path.abspath(sys.argv[2])
sys.path.insert(0, os.getcwd())

from services.search_service import normalize


COVERED_BELOW = 0x3000


def fold_char(char):
    """`normalize` minus its final whitespace collapse, for one character."""
    folded = unicodedata.normalize("NFKD", char.casefold())
    stripped = "".join(ch for ch in folded if not unicodedata.combining(ch))
    return stripped.replace("ı", "i")


def rebuilt(text):
    """What the Dart port will compute: fold each character, then collapse."""
    joined = "".join(
        fold_char(char) if ord(char) < COVERED_BELOW else char
        for char in text
    )
    return " ".join(joined.split())


# --- the equivalence check, before anything is written ---------------------

covered = [
    cp for cp in range(COVERED_BELOW)
    # Surrogates are not characters and `chr()` on one is not text.
    if not (0xD800 <= cp <= 0xDFFF)
]

for cp in covered:
    char = chr(cp)
    if normalize(char) != rebuilt(char):
        raise SystemExit(
            f"per-character folding disagrees at U+{cp:04X}: "
            f"{normalize(char)!r} != {rebuilt(char)!r}"
        )

random.seed(20260827)
for _ in range(60000):
    sample = "".join(
        chr(random.choice(covered)) for _ in range(random.randint(1, 6))
    )
    if normalize(sample) != rebuilt(sample):
        raise SystemExit(
            f"per-character folding disagrees on {sample!r}: "
            f"{normalize(sample)!r} != {rebuilt(sample)!r}"
        )


# --- the table -------------------------------------------------------------

entries = []
for cp in covered:
    char = chr(cp)
    folded = fold_char(char)
    if folded != char:
        entries.append((cp, folded))

whitespace = [cp for cp in range(0x110000) if chr(cp).isspace()]


def dart_string(value):
    out = []
    for char in value:
        if char == "\\":
            out.append("\\\\")
        elif char == "'":
            out.append("\\'")
        elif char == "$":
            out.append("\\$")
        elif ord(char) < 0x20 or ord(char) == 0x7F:
            out.append(f"\\u{{{ord(char):x}}}")
        else:
            out.append(char)
    return "'" + "".join(out) + "'"


with open(table_path, "w", encoding="utf-8") as handle:
    handle.write(f'''/// The character folding behind search, generated from the desktop's own
/// `normalize()`.
///
/// GENERATED by `tool/emit_search_folding.py` from
/// `services/search_service.py`. Do not edit: the point of the file is that
/// nobody transcribed it. Dart has no Unicode normalisation in its core
/// library and this project takes no dependency for one, so the desktop's
/// `casefold` -> NFKD -> drop-combining -> `ı`->`i` chain is precomputed here
/// for every character it changes.
///
/// The generator PROVES, before writing this, that folding character by
/// character and collapsing whitespace afterwards gives the same answer as
/// running the desktop's whole-string function — over every covered codepoint
/// and over 60,000 random strings built from them.
///
/// **Coverage stops at U+{COVERED_BELOW:04X}**, and a character above it passes
/// through untouched. That is the safe direction: everything a Turkish
/// household types into an account name, a category or a description lives far
/// below it, and the failure mode for anything else is a search that does not
/// match rather than one that matches the wrong thing.
library;

/// Codepoint -> what it folds to. A codepoint absent from this map below
/// U+{COVERED_BELOW:04X} folds to itself.
const Map<int, String> searchFolding = {{
''')
    for cp, folded in entries:
        handle.write(f"  0x{cp:04X}: {dart_string(folded)},\n")
    handle.write("};\n\n")
    handle.write(f"/// The highest codepoint [searchFolding] speaks for.\n")
    handle.write(f"const int searchFoldingCoveredBelow = 0x{COVERED_BELOW:04X};\n\n")
    handle.write(
        "/// Every codepoint Python's `str.split()` treats as whitespace, which\n"
        "/// is what the desktop collapses runs of. Dart's `\\s` is ASCII-only by\n"
        "/// default and would leave a non-breaking space in the middle of a\n"
        "/// normalised name.\n"
        "const Set<int> searchWhitespace = {\n"
    )
    for cp in whitespace:
        handle.write(f"  0x{cp:04X},\n")
    handle.write("};\n")


# --- vectors, over strings rather than characters --------------------------

CASES = [
    # The Turkish i's, every direction. This is where search breaks most.
    "ISI", "ısı", "Isı", "İSİ", "isi", "İstanbul", "istanbul", "ISTANBUL",
    # Accented letters typed without their accents.
    "Şirket", "sirket", "Günlük", "gunluk", "Öğrenci", "ogrenci",
    "Çocuk", "cocuk", "ÇOCUK",
    # Real category names out of the seed.
    "Maaş", "maas", "MAAŞ", "Ev Kirası", "ev kirasi", "Kıdem Tazminatı",
    "Doğalgaz", "dogalgaz", "İnternet", "internet", "Sağlık", "saglik",
    # Whitespace: leading, trailing, runs, tabs, and a non-breaking space.
    "  Maaş  ", "Ev\tKirası", "Ev   Kirası", "Ev Kirası", "\n Maaş \n",
    # Already-decomposed input: base letter plus a combining mark.
    "Şirket", "Günlük",
    # Nothing, and nothing but space.
    "", "   ", "\t\n",
    # A sharp s, which casefold EXPANDS rather than maps — inside coverage.
    "Straße",
    # A ligature, which is NOT: U+FB01 sits above the table, so this is the
    # one case in this list the port is expected to get differently. It is
    # here on purpose, to keep that gap measured rather than forgotten.
    "ﬁnans",
    # Digits and punctuation, which must survive untouched.
    "2026-08", "%50", "A/B",
]

with open(vectors_path, "w", encoding="utf-8") as handle:
    handle.write(
        "# CASE|input|normalized — generated by "
        "services/search_service.py's normalize()\n"
    )
    handle.write(
        "# DIVERGES|input|desktop|port — an input the port CANNOT match, "
        "because the character is above the folding table's coverage. "
        "Measured, not assumed: if coverage widens these lines disappear.\n"
    )
    handle.write(
        "# fields are backslash-escaped: \\n \\t \\\\ and \\uXXXX for anything "
        "else non-printing or non-ASCII-space\n"
    )

    def escape(value):
        out = []
        for char in value:
            if char == "\\":
                out.append("\\\\")
            elif char == "|":
                out.append("\\u007C")
            elif char == "\n":
                out.append("\\n")
            elif char == "\t":
                out.append("\\t")
            elif char.isspace() and char != " ":
                out.append(f"\\u{ord(char):04X}")
            elif ord(char) < 0x20:
                out.append(f"\\u{ord(char):04X}")
            else:
                out.append(char)
        return "".join(out)

    diverging = 0
    for case in CASES:
        desktop = normalize(case)
        ours = rebuilt(case)
        if desktop == ours:
            handle.write(f"CASE|{escape(case)}|{escape(desktop)}\n")
        else:
            diverging += 1
            handle.write(
                f"DIVERGES|{escape(case)}|{escape(desktop)}|{escape(ours)}\n"
            )

print(
    f"{len(entries)} folding entries, {len(CASES)} vectors, "
    f"{diverging} of them outside coverage"
)
